### ISSUE TITLE
Messaging sendAll() does not return correct feedback when there's an errorneous request

### ISSUE THREAD

**Issue by bds-viktoras** [kreait/firebase-bundle#15]
When using messaging component's `sendAll()` method to attempt sending multiple messages at once, if at least one of those messages bounces or there's an issue with FCM token, then the returned `MulticastSendReport` object is always empty. 

In case there are no issues with any of sub-requests, the returned `MulticastSendReport` object contains all the feedback correctly.

**Comment by jeromegamez** [comment]
The `sendAll()` method currently needs to return a `MulticastSendReport` because of backward compatibility reasons, so it might be that not everything is included there, but could you be more specific on what's missing exactly?

I just tried with the following and got what I expected

```php
$factory = (new Factory())->withServiceAccount('/path/to/firebase_service_account.json');
$messaging = $factory->createMessaging();

$messages = [
    ['token' => $androidToken, 'notification' => ['title' => 'Android title']],
    ['token' => 'failure', 'notification' => ['title' => 'Failed title']],
    ['token' => $testToken, 'notification' => ['title' => 'Test title']],
];

try {
    $report = $messaging->sendAll($messages);
} catch (MessagingException $e) {
    echo $e->getMessage();
    exit;
}


print_r([
    'failures' => $report->failures()->count(),
    'successes' => $report->successes()->count(),
]);

foreach ($report->failures()->getItems() as $failure) {
    echo $failure->error()->getMessage().PHP_EOL;
}
```
⬇️
```
❯ php test.php
Array
(
    [failures] => 1
    [successes] => 2
)
The registration token is not a valid FCM registration token
```

**Comment by bds-viktoras** [comment]
Running the exact same code as in your example returns an empty feedback list:
```
MulticastSendReport {#914
  -items: []
}
```

If the line with incorrect token is removed, then feedback array returns two items with their information.

In both cases two notifications are being delivered. so middle line failure does affect status reporting, but not the actual send process.

**Comment by srsagor007** [comment]
when try to using sendMulticast showing that error 

$all_data = array_chunk($recipients, 500);
                    
            foreach ($all_data as $deviceTokens) { 
                $message = CloudMessage::new()
                            ->withNotification($notification)
                            ->withData([
                                'notification_id' => $notification_id,
                                'activity' => $category,
                                'sub_activity' => $sub_category,
                                'subject_id' => $subject_id,
                            ]);         
                $result = $messaging->sendMulticast($message, $deviceTokens); // Pass the array of device tokens here            
            }

-error: Kreait\Firebase\Exception\Messaging\MessagingError {#6562 ▼
        #message: "Operation is not implemented, or supported, or enabled."
        #code: 501
        #file: "C:\xampp\htdocs\sajida-fieldforce\vendor\kreait\firebase-php\src\Firebase\Exception\Messaging\MessagingError.php"
        #line: 22
        #errors: array:1 [▼
          "error" => array:3 [▼
            "code" => 501
            "message" => "Operation is not implemented, or supported, or enabled."
            "status" => "UNIMPLEMENTED"
          ]
        ]

**Comment by jeromegamez** [comment]
This is a 5+ year old issue 😅. You are using an old version of the Bundle or the SDK and need to update to the latest versions.

**Comment by asif-ca** [comment]
@jeromegamez I am using `"kreait/firebase-php": "^5.26"` in laravel  6 and PHP 7.4 (that's the only supported package version with this env) and I am getting an empty report.

```
Kreait\Firebase\Messaging\MulticastSendReport {#4208 ▼
  -items: []
}
```
and the **send** method is working fine which sends messages one by one (so not scalable) with same package version 


**is there any workaround for this?**

**Comment by jeromegamez** [comment]
See https://github.com/kreait/firebase-bundle/issues/65
