### ISSUE TITLE
Compatibiliy for symfony 5

### ISSUE THREAD

**Issue by Khatib-Abbas** [kreait/firebase-bundle#17]
Hi,
When i want to install this bundle i got this errors
Thanks in advance for your help

 Problem 1
    - kreait/firebase-bundle 1.6.1 requires symfony/dependency-injection ^2.8.50|^3.4.26|^4.1.12 -> no matching package found.
    - kreait/firebase-bundle 1.6.0 requires symfony/dependency-injection ^2.8|^3.4|^4.0 -> no matching package found.
    - Installation request for kreait/firebase-bundle ^1.6 -> satisfiable by kreait/firebase-bundle[1.6.0, 1.6.1].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by jeromegamez** [comment]
I‘ll update the dependency requirements soon, but I‘m also open for a pull request 😅

**Comment by jeromegamez** [comment]
I just released [1.7.0](https://github.com/kreait/firebase-bundle/releases/tag/1.7.0), please let me know if something doesn't work after the update. 🤞
