### ISSUE TITLE
There is no extension able to load the configuration for "kreait_firebase"

### ISSUE THREAD

**Issue by picks44** [kreait/firebase-bundle#25]
## The problem

Trying to add and configure this bundle to a Symfony 3.4 project and getting this error on cache clear : `There is no extension able to load the configuration for "kreait_firebase" (in "C:\laragon\www\DESiwid\app/config\config.yml"). Looked for namespace "kreait_firebase", found ""framework", "security", "twig", "monolog", "swiftmailer", "doctrine", "sensio_framework_extra", "des_iwid", "bazinga_js_translation", "cspoo_swiftmailer_mailgun", "exercise_html_purifier", "fm_elfinder", "fos_js_routing", "fos_user", "fresh_vich_uploader_serialization", "isometriks_spam", "ivory_ck_editor", "jms_aop", "jms_di_extra", "jms_i18n_routing", "jms_serializer", "jms_translation", "knp_menu", "knpu_oauth2_client", "lexik_jwt_authentication", "liip_imagine", "google_analytics_api", "nelmio_cors", "stof_doctrine_extensions", "assetic", "vich_uploader", "debug", "web_profiler", "sensio_distribution", "web_server"".`

## Environment

- PHP Version (`php -v`): PHP 7.2.16 (cli)
- Firebase PHP SDK and Bundle version (`composer show | grep kreait`):

kreait/clock                             1.0.1   A PHP 7.0 compatible clock abstraction
kreait/firebase-bundle                   2.0.0   Symfony Bundle for the Firebase Admin SDK
kreait/firebase-php                      5.2.0   Firebase Admin SDK
kreait/firebase-tokens                   1.10.0  A library to work with Firebase tokens

**Comment by jeromegamez** [comment]
Just to be sure: have you added the bundle to your AppKernel?

**Comment by picks44** [comment]
@jeromegamez I'm an idiot (or I'm already too much used to Flex). Thanks.

**Comment by jeromegamez** [comment]
It happens to me more often than I'd like to admit as well 🙈
