### ISSUE TITLE
PHP 8 Support

### ISSUE THREAD

**Issue by SherinBloemendaal** [kreait/firebase-bundle#34]
## The problem

composer require throws an error when running php 8.0.

## Environment

- PHP Version (`php -v`): 8.0
- Firebase PHP SDK and Bundle version (`composer show | grep kreait`): (latest)

## Details

Is PHP 8 already supported?

**Comment by jeromegamez** [comment]
"(latest)" is not a version number. 

Yes, the Bundle and underlying SDK support PHP 8.

When creating an issue, please make sure it's actionable, I'm not sure what you expected me to do here.

**Comment by SherinBloemendaal** [comment]
Ok thanks
