### ISSUE TITLE
Failed to load class Google\Cloud\Firestore\FirestoreClient used by typed property Kreait\Firebase\Firestore::$client during preloading

### ISSUE THREAD

**Issue by badr-ou** [kreait/firebase-bundle#35]
## Describe the issue you are experiencing

Hi there,

I'm getting this error, when i apply  `composer dump-autoload -o --no-dev` or  `composer dump-autoload --classmap-authoritative --no-dev` during the build of my container and i run it but when i apply `composer dump-autoload -o`  it works perfectly.

I only use cloud messaging service.

Thanks.

## Installed packages
- kreait/firebase-bundle 2.4
## PHP version and extensions
- PHP 8.0
- API Platform
- Docker

## Error message/Stack trace
`NOTICE: PHP message: PHP Fatal error:  Failed to load class Google\Cloud\Firestore\FirestoreClient used by typed property Kreait\Firebase\Firestore::$client during preloading in Unknown on line 0`

**Comment by badr-ou** [comment]
It's solved, it was a symfony environment problem.

**Comment by dsech** [comment]
@blt909 Thanks, I think I'm encountering a different issue then, because the env is built and warmed up in my case, and the error appears only when using `opcache.preload=/app/config/preload.php` in php-fpm. My current workaround is to not use preloading at all, which isn't ideal.

I will debug some more to find what is my issue.

**Comment by dsech** [comment]
I found a workaround by configuring `public: false` inside `firebase.yaml`. 
This way Symfony did not include anymore the unused `Kreait\Firebase\Firestore` class in the preload script.

I suppose it would be nice to avoid this issue, by having `public: false` by default, or have an option to enable each service separately?

**Comment by ThomasBerends** [comment]
For me I had to do the following:
```composer require google/cloud-firestore```

This package was not installed for some reason.
