### ISSUE TITLE
Feature request: support for FCM localization

### ISSUE THREAD

**Issue by marcoberetta96** [kreait/firebase-bundle#39]
Hi. It seems that FCM localization is not supported by this library.
I'm referring to the parameters body_loc_key, body_loc_args, title_loc_key, title_loc_args.
Are you going to add support for this?
Thanks

**Comment by jeromegamez** [comment]
Hey there 👋!

You can add platform-specific parameters, including those you mentioned, by following the [SDK's docs](https://firebase-php.readthedocs.io/en/5.x/cloud-messaging.html#adding-target-platform-specific-configuration), there you will you can find further links to the platform-specific payload references ([Android](https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#androidconfig), [APNS](https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/PayloadKeyReference.html#//apple_ref/doc/uid/TP40008194-CH17-SW1)).

Please note that this SDK uses the [HTTP V1 API](https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages), not the [Legacy HTTP Server Protocol](https://firebase.google.com/docs/cloud-messaging/http-server-ref).
