### ISSUE TITLE
Where is the file FirebaseBundle.php ?

### ISSUE THREAD

**Issue by youngdreamer33** [kreait/firebase-bundle#5]
Hello,

I've been learning PHP with Symfony for a few months and want to add Firebase to my project (which I'm learning !).
There are new issues with the last version of Symfony with bundles (https://stackoverflow.com/questions/44928982/appkernel-php-weird-behavior#comment76834486_44928982)  and I cannot fix it for your bundle.
The installation of the bundle crashes my project and I cannot find the file FirebaseBundle.php which is referred to in the AppKernel.php.

I don't know if I'm clear enough but I'd love if you could help me out ! 

Thanks for your bundle and the sdk anyway ! :)

**Comment by jeromegamez** [comment]
Hey @youngdreamer33,

there is no 1.0 release yet, in the meantime you can install it with

```bash
composer require kreait/firebase-bundle 1.0.x-dev
```

or insert 

```
"kreait/firebase-bundle": "1.0.x-dev",
```

in your `composer.json` followed by a `composer update`.

**Comment by youngdreamer33** [comment]
Thanks, this is what I did.
When I run the server I got this message: 



 [LogicException]
 Users will expect the alias of the default extension of a bundle to be the underscored version of the bundle name (
 "firebase"). You can override "Bundle::getContainerExtension()" if you want to use "kreait_firebase" or another alias.

Do you know how and where I can override it by any chance ? :)

**Comment by jeromegamez** [comment]
Yes, this was a bug that I fixed a couple of minutes ago 🙈, please try a `composer update` to get the latest files  :)

**Comment by youngdreamer33** [comment]
Thanks but now I got this error:   
 [Symfony\Component\Config\Definition\Exception\InvalidTypeException]
  Invalid type for path "kreait_firebase.projects.third". Expected array, but got string 
^^
Sorry for the inconvenience !

**Comment by jeromegamez** [comment]
No problem @youngdreamer33 :). The snippet in the README is just an example to show that you can define multiple projects. Here is a minimal example:

```yml
kreait_firebase:
    projects:
        my_project: # <- you can name this whatever you want
            database_uri: 'https://my_project.firebaseio.com'
            api_key: '<api_key>'
```

You just have to replace the values for `database_uri` and `api_key` with the actual values from project.

**Comment by youngdreamer33** [comment]
Thanks !! I didn't think it was an issue in config.yml but with your explanation I understand better how the bundle works so thanks a lot for your help !

**Comment by jeromegamez** [comment]
You're welcome! 🌺
